name: Deploy to EC2

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > key.pem
          chmod 400 key.pem

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem -r ./path_to_your_script ec2-user@your_ec2_ip:/path_on_ec2
